---
title: "MP2"
author: "Tingwei Hu, Eugene Yang, Anya Zhong, Andriana Patmanidis"
date: "2023-02-14"
output: html_document
bibliography: BIOL5380.bib
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(av)
library(ggpubr)
library(car)
```


```{r,more processing, message=FALSE}
walk.files <- list.files()[grep("walk_.*.txt",list.files())]
print(walk.files)

walk.dat <- list() #make a list for storing
for(i in walk.files){
  walk.i <- read_delim(i,delim="\t") #read data as a tibble
  met.dat <- unlist(strsplit(i,"_")) #split i for metadata and unlist it
  speed <- met.dat[2] #get speed
  subject <- gsub(".txt","",met.dat[3]) #remove ".txt" 
  walk.dat[[i]] <- walk.i%>%
    mutate(speed=speed,subject=subject)
}
```

```{r,combine}
walk.dat <- do.call(rbind,walk.dat)
head(walk.dat)
```
```{r,ok}
colnames(walk.dat) <- str_remove(colnames(walk.dat)," \\[pixel\\]| \\[sec\\]")
head(walk.dat)
```
```{r,plot}
walk.dat2 <- walk.dat%>%
  select(TID,PID,x,y,subject,speed)
walk.dat2%>%
  ggplot(aes(x,y,col=speed))+geom_point()+facet_grid(subject~.)
```
```{r,more plots}
walk.dat2 <- walk.dat2%>%
  group_by(speed,subject)%>%
  mutate(y=abs(y-max(y)))
walk.dat2%>%
  ggplot(aes(x,y,col=speed))+geom_point()+facet_grid(subject~.)#grid it with columns = to speed

```

```{r,more}
walk.dat2 <- walk.dat2%>%
  mutate(TID=replace(TID, TID==1, "hipR"))%>%
  mutate(TID=replace(TID, TID==2, "hipC"))
head(walk.dat2)
```
```{r,pivot wide}
walk.wide <- walk.dat2%>%
  pivot_wider(names_from=TID,values_from=c("x","y"))
head(walk.wide)
```

```{r,tilt angle}
walk.wide <- walk.wide %>%
  mutate(angle = atan(abs(x_hipR-x_hipC)/abs(y_hipR-y_hipC))*180/pi)
```

```{r,max tilt angle}
walk.wide.max <- walk.wide %>% 
  group_by(subject,speed) %>% 
  drop_na(angle) %>% 
  summarise(max=max(angle))
walk.wide.max
```

```{r}
class.gait <- read_csv('class_gait.csv') %>% 
  na.omit()
class.gait
```

# Report Question 2
```{r}
class.gait %>% 
  ggplot(aes(x=leg_length_m,y=`recorded_walking_ms^-1`,col=sex))+geom_point()+
  xlab('Leg Length (m)')+
  ylab('Recorded Pendulum Walking Speed (m/s)')+
  ggtitle('Size vs. Pendulum Walking Speed by Sex')

#gait by sex (only) boxplot
class.gait %>% 
  ggplot(aes(x=sex,y=`recorded_walking_ms^-1`))+geom_boxplot()+
  stat_compare_means(method ='t.test')

#leg length by sex
t.test(leg_length_m~sex,data=class.gait)

#analysis of covariance: Vwalking ~ sex + leg_length_m
ancova_model <- aov(`recorded_walking_ms^-1` ~ sex + leg_length_m, data = class.gait)
Anova(ancova_model, type="III") 

```


# Report Question 4
```{r, Mass Plot}
ggplot(class.gait, aes(x= Mass_Kg, y= norm_mean_max_pt_angle, color= sex))+geom_point()+ylab("Normal Mean Maximum Pelvic Tilt (deg)") + xlab("Mass (kg)")

```

***Figure ***

```{r, Length Plot}
ggplot(class.gait, aes(x= leg_length_m, y= norm_mean_max_pt_angle, color= sex))+geom_point() + ylab("Normal Mean Maximum Pelvic Tilt (deg)") + xlab("Leg Length (m)")
```

# References
